import math

TWO_BITS_WITH = 2
FOUR_BITS_WIDTH = 4
EIGHT_BITS_WIDTH = 8
FIVE_BITS_WIDTH = 5
SEVEN_BITS_WIDTH = 7

LEFT_SPACE = 125


buses_metadata = {
    "A": {"width": 30},
    "D": {"width": 25},
    "B": {"width": 18},
    "C": {"width": 48},
    "O": {"width": 48},
}


configurations = [
    {
        "name": "int4",
        "mult1": [
            {
                "signed": False,
                "num_width": FOUR_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, FOUR_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": FOUR_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, FOUR_BITS_WIDTH)) - 1,
                "phase": 22,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": FOUR_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, FOUR_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": FOUR_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, FOUR_BITS_WIDTH)) - 1,
                "phase": 11,
                "label": "d",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int8_18",
        "mult1": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 18,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int8_19",
        "mult1": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 19,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int8_21",
        "mult1": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 21,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int8_20",
        "mult1": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 20,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": EIGHT_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, EIGHT_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int5",
        "mult1": [
            {
                "signed": False,
                "num_width": FIVE_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, FIVE_BITS_WIDTH)) - 1,
                "phase": 24,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": FIVE_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, FIVE_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": FIVE_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, FIVE_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": FIVE_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, FIVE_BITS_WIDTH)) - 1,
                "phase": 12,
                "label": "d",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int2",
        "mult1": [
            {
                "signed": False,
                "num_width": TWO_BITS_WITH,
                "bus": "A",
                "number": int(math.pow(2, TWO_BITS_WITH)) - 1,
                "phase": 24,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": TWO_BITS_WITH,
                "bus": "A",
                "number": int(math.pow(2, TWO_BITS_WITH)) - 1,
                "phase": 12,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": TWO_BITS_WITH,
                "bus": "A",
                "number": int(math.pow(2, TWO_BITS_WITH)) - 1,
                "phase": 0,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": TWO_BITS_WITH,
                "bus": "B",
                "number": int(math.pow(2, TWO_BITS_WITH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": TWO_BITS_WITH,
                "bus": "B",
                "number": int(math.pow(2, TWO_BITS_WITH)) - 1,
                "phase": 6,
                "label": "d",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int7_22",
        "mult1": [
            {
                "signed": False,
                "num_width": SEVEN_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, SEVEN_BITS_WIDTH)) - 1,
                "phase": 22,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": SEVEN_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, SEVEN_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": SEVEN_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, SEVEN_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
    {
        "name": "int7_23",
        "mult1": [
            {
                "signed": False,
                "num_width": SEVEN_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, SEVEN_BITS_WIDTH)) - 1,
                "phase": 23,
                "label": "a",
                "MSB_position": 0,
                "LSB position": 0,
            },
            {
                "signed": False,
                "num_width": SEVEN_BITS_WIDTH,
                "bus": "A",
                "number": int(math.pow(2, SEVEN_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "b",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
        "mult2": [
            {
                "signed": False,
                "num_width": SEVEN_BITS_WIDTH,
                "bus": "B",
                "number": int(math.pow(2, SEVEN_BITS_WIDTH)) - 1,
                "phase": 0,
                "label": "c",
                "MSB_position": 0,
                "LSB position": 0,
            },
        ],
    },
]
