configurations = [
    {
        "name": "int4",
        "mult1": [
            {
                "bus": "A",
                "num_width": 4,
                "phase": 0,
                "label": "a",
                "signed": True,
                "number": 7,
            },
            {
                "bus": "D",
                "num_width": 4,
                "phase": 22,
                "label": "b",
                "signed": True,
                "number": 7,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 4,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 7,
            },
            {
                "bus": "B",
                "num_width": 4,
                "phase": 11,
                "label": "d",
                "signed": True,
                "number": 7,
            },
        ],
    },
    {
        "name": "int8_18",
        "mult1": [
            {
                "bus": "D",
                "num_width": 8,
                "phase": 0,
                "label": "a",
                "signed": True,
                "number": 127,
            },
            {
                "bus": "A",
                "num_width": 8,
                "phase": 18,
                "label": "b",
                "signed": True,
                "number": 127,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 8,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 127,
            },
        ],
    },
    {
        "name": "int8_19",
        "mult1": [
            {
                "bus": "D",
                "num_width": 8,
                "phase": 0,
                "label": "a",
                "signed": True,
                "number": 127,
            },
            {
                "bus": "A",
                "num_width": 8,
                "phase": 19,
                "label": "b",
                "signed": True,
                "number": 127,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 8,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 127,
            },
        ],
    },
    {
        "name": "int8_21",
        "mult1": [
            {
                "bus": "D",
                "num_width": 8,
                "phase": 0,
                "label": "a",
                "signed": True,
                "number": 127,
            },
            {
                "bus": "A",
                "num_width": 8,
                "phase": 21,
                "label": "b",
                "signed": True,
                "number": 127,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 8,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 127,
            },
        ],
    },
        {
        "name": "int8_20",
        "mult1": [
            {
                "bus": "D",
                "num_width": 8,
                "phase": 0,
                "label": "a",
                "signed": True,
                "number": 127,
            },
            {
                "bus": "A",
                "num_width": 8,
                "phase": 20,
                "label": "b",
                "signed": True,
                "number": 127,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 8,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 127,
            },
        ],
    },
    {
        "name": "int5",
        "mult1": [
            {
                "bus": "A",
                "num_width": 5,
                "phase": 24,
                "label": "a",
                "signed": True,
                "number": 15,
            },
            {
                "bus": "D",
                "num_width": 5,
                "phase": 0,
                "label": "b",
                "signed": True,
                "number": 15,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 5,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 15,
            },
            {
                "bus": "B",
                "num_width": 5,
                "phase": 12,
                "label": "d",
                "signed": True,
                "number": 15,
            },
        ],
    },
    {
        "name": "int2",
        "mult1": [
            {
                "bus": "A",
                "num_width": 2,
                "phase": 24,
                "label": "a",
                "signed": True,
                "number": 1,
            },
            {
                "bus": "A",
                "num_width": 2,
                "phase": 12,
                "label": "b",
                "signed": True,
                "number": 1,
            },
            {
                "bus": "D",
                "num_width": 2,
                "phase": 0,
                "label": "b",
                "signed": True,
                "number": 1,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 2,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 1,
            },
            {
                "bus": "B",
                "num_width": 2,
                "phase": 6,
                "label": "d",
                "signed": True,
                "number": 1,
            },
        ],
    },
    {
        "name": "int7_22",
        "mult1": [
            {
                "bus": "A",
                "num_width": 7,
                "phase": 22,
                "label": "a",
                "signed": True,
                "number": 63,
            },
            {
                "bus": "D",
                "num_width": 7,
                "phase": 0,
                "label": "b",
                "signed": True,
                "number": 63,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 7,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 63,
            },
        ],
    },
    {
        "name": "int7_23",
        "mult1": [
            {
                "bus": "A",
                "num_width": 7,
                "phase": 23,
                "label": "a",
                "signed": True,
                "number": 63,
            },
            {
                "bus": "D",
                "num_width": 7,
                "phase": 0,
                "label": "b",
                "signed": True,
                "number": 63,
            },
        ],
        "mult2": [
            {
                "bus": "B",
                "num_width": 7,
                "phase": 0,
                "label": "c",
                "signed": True,
                "number": 63,
            },
        ],
    },
]
